[development]
address = "localhost"
port = 8000
workers = 2
keep_alive = 5
read_timeout = 5
write_timeout = 5
log = "normal"
secret_key = "8Xui8SN4mI+7egV/9dlfYYLGQJeEx4+DwmSQLwDVXJg="
limits = { forms = 32768 }

[staging]
address = "0.0.0.0"
port = 8000
workers = 1
keep_alive = 5
read_timeout = 5
write_timeout = 5
log = "normal"
secret_key = "8Xui8SN4mI+7egV/9dlfYYLGQJeEx4+DwmSQLwDVXJg="
limits = { forms = 32768 }

[production]
address = "0.0.0.0"
port = 8000
workers = 2
keep_alive = 5
read_timeout = 5
write_timeout = 5
log = "critical"
secret_key = "8Xui8SN4mI+7egV/9dlfYYLGQJeEx4+DwmSQLwDVXJg="
limits = { forms = 32768 }